# Generated by Django 5.0.4 on 2024-05-04 08:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('malumotlar', '0001_initial'),
        ('xizmat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ziyoratgoh',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(max_length=300)),
                ('rasm_first', models.ImageField(upload_to='rasmlar/')),
                ('rasm_second', models.ImageField(upload_to='rasmlar/')),
                ('about', models.TextField(blank=True)),
                ('mehmonxona', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='xizmat.mehmonxona')),
                ('oshxona', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='xizmat.oshxona')),
                ('shifoxona', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='xizmat.ustaxona')),
                ('tuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malumotlar.district')),
                ('ustaxona', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='xizmat.shifoxona')),
                ('viloyat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malumotlar.region')),
            ],
        ),
    ]
