# Generated by Django 5.0.4 on 2024-05-04 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xizmat', '0001_initial'),
        ('ziyoratgoh', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ziyoratgoh',
            name='shifoxona',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='xizmat.shifoxona'),
        ),
        migrations.AlterField(
            model_name='ziyoratgoh',
            name='ustaxona',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='xizmat.ustaxona'),
        ),
    ]
