# Generated by Django 5.0.4 on 2024-05-04 09:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ziyoratgoh', '0002_alter_ziyoratgoh_shifoxona_alter_ziyoratgoh_ustaxona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carusel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ziyoratgoh', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ziyoratgoh.ziyoratgoh')),
            ],
        ),
    ]
