# Generated by Django 5.0.4 on 2024-05-04 08:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('malumotlar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mehmonxona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomi', models.CharField(max_length=255)),
                ('ochilish_vaqti', models.TimeField()),
                ('yopilish_vaqti', models.TimeField()),
                ('telefon_raqam', models.CharField(max_length=15)),
                ('joylashuv', models.CharField(max_length=400)),
                ('ish_kunlari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malumotlar.ish_kuni')),
                ('tuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malumotlar.district')),
                ('viloyat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malumotlar.region')),
            ],
        ),
        migrations.CreateModel(
            name='Oshxona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomi', models.CharField(max_length=255)),
                ('ochilish_vaqti', models.TimeField()),
                ('yopilish_vaqti', models.TimeField()),
                ('telefon_raqam', models.CharField(max_length=15)),
                ('joylashuv', models.CharField(max_length=400)),
                ('ish_kunlari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malumotlar.ish_kuni')),
                ('tuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malumotlar.district')),
                ('viloyat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malumotlar.region')),
            ],
        ),
        migrations.CreateModel(
            name='Shifoxona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomi', models.CharField(max_length=255)),
                ('ochilish_vaqti', models.TimeField()),
                ('yopilish_vaqti', models.TimeField()),
                ('telefon_raqam', models.CharField(max_length=15)),
                ('joylashuv', models.CharField(max_length=400)),
                ('ish_kunlari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malumotlar.ish_kuni')),
                ('tuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malumotlar.district')),
                ('viloyat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malumotlar.region')),
            ],
        ),
        migrations.CreateModel(
            name='Ustaxona',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nomi', models.CharField(max_length=255)),
                ('ochilish_vaqti', models.TimeField()),
                ('yopilish_vaqti', models.TimeField()),
                ('telefon_raqam', models.CharField(max_length=15)),
                ('joylashuv', models.CharField(max_length=400)),
                ('ish_kunlari', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malumotlar.ish_kuni')),
                ('tuman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malumotlar.district')),
                ('viloyat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='malumotlar.region')),
            ],
        ),
    ]
